# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            nacmacfeegle
tagline:          developer blog
url:              http://nacmacfeegle.github.io
paginate:         1
baseurl:          http://nacmacfeegle.github.io/
author:
  name:           danc
  url:            https://twitter.com/danc_ie
  email:          notgiven@gmail.com

# Custom vars
version:          0.1
github:
  repo:           https://github.com/nacmacfeegle/nacmacfeegle.github.io
